DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  img_url TEXT NOT NULL,
  rating TEXT NOT NULL,
  price TEXT NOT NULL,
  in_stock BOOLEAN
)